version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-stable
    restart: unless-stopped
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - laravel-net

  db:
    image: mysql:latest
    container_name: laravel-mysql-stable
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33066:3306"
    networks:
      - laravel-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel-phpmyadmin-stable
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - laravel-net
    depends_on:
      - db

networks:
  laravel-net:
    driver: bridge

volumes:
  db_data:
    driver: local